[2024-06-02T20:31:35.453+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:31:35.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:31:35.457+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:31:35.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:31:35.476+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:31:35.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:31:35.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:31:35.514+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.067 seconds
[2024-06-02T20:32:05.914+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:32:05.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:32:05.918+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:32:05.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:32:05.936+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:32:05.931+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:32:05.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:32:05.968+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.059 seconds
[2024-06-02T20:32:36.667+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:32:36.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:32:36.669+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:32:36.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:32:36.690+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:32:36.685+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:32:36.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:32:36.721+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.059 seconds
[2024-06-02T20:33:06.990+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:33:06.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:33:06.993+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:33:06.993+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:33:07.009+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:33:07.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:33:07.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:33:07.046+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.060 seconds
[2024-06-02T20:33:37.195+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:33:37.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:33:37.198+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:33:37.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:33:37.214+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:33:37.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:33:37.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:33:37.252+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.062 seconds
[2024-06-02T20:34:07.405+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:34:07.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:34:07.407+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:34:07.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:34:07.422+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:34:07.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:34:07.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:34:07.454+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.054 seconds
[2024-06-02T20:34:37.683+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:34:37.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:34:37.686+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:34:37.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:34:37.702+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:34:37.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:34:37.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:34:37.734+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.055 seconds
[2024-06-02T20:35:07.925+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:35:07.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:35:07.927+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:35:07.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:35:07.944+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:35:07.940+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:35:07.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:35:07.973+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.054 seconds
[2024-06-02T20:35:38.170+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:35:38.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:35:38.173+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:35:38.173+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:35:38.190+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:35:38.186+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:35:38.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:35:38.226+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.060 seconds
[2024-06-02T20:36:08.433+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:36:08.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:36:08.436+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:36:08.435+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:36:08.454+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:36:08.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:36:08.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:36:08.488+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.063 seconds
[2024-06-02T20:36:38.721+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:36:38.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:36:38.723+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:36:38.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:36:38.741+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:36:38.737+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:36:38.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:36:38.773+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.057 seconds
[2024-06-02T20:37:09.004+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:37:09.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:37:09.010+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:37:09.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:37:09.040+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:37:09.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:37:09.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:37:09.087+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.095 seconds
[2024-06-02T20:37:39.297+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:37:39.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:37:39.305+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:37:39.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:37:39.327+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:37:39.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 1, in <module>
    from datetime import timdelta
ImportError: cannot import name 'timdelta' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-02T20:37:39.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:37:39.378+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.097 seconds
[2024-06-02T20:38:04.887+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:04.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:38:04.893+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:38:04.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:04.924+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:38:04.920+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from extract import run_nba_etl
ModuleNotFoundError: No module named 'extract'
[2024-06-02T20:38:04.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:04.962+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.082 seconds
[2024-06-02T20:38:08.892+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:08.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:38:08.896+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:38:08.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:08.929+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:38:08.924+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from extract import run_nba_etl
ModuleNotFoundError: No module named 'extract'
[2024-06-02T20:38:08.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:08.966+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.081 seconds
[2024-06-02T20:38:39.676+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:39.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:38:39.678+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:38:39.678+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:39.695+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:38:39.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from extract import run_nba_etl
ModuleNotFoundError: No module named 'extract'
[2024-06-02T20:38:39.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:38:39.725+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.053 seconds
[2024-06-02T20:39:26.597+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:39:26.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:39:26.601+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:39:26.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:39:26.619+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:39:26.615+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from extract import run_nba_etl
ModuleNotFoundError: No module named 'extract'
[2024-06-02T20:39:26.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:39:26.650+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.058 seconds
[2024-06-02T20:39:57.004+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:39:57.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:39:57.017+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:39:57.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:39:57.226+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:39:57.204+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from extract import run_nba_etl
ModuleNotFoundError: No module named 'extract'
[2024-06-02T20:39:57.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:39:57.448+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.464 seconds
[2024-06-02T20:40:28.136+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:28.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:40:28.139+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:40:28.139+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:28.157+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:40:28.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from extract import run_nba_etl
ModuleNotFoundError: No module named 'extract'
[2024-06-02T20:40:28.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:28.192+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.063 seconds
[2024-06-02T20:40:54.290+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:54.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:40:54.294+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:40:54.293+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:54.323+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:40:54.319+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA import run_nba_etl
ModuleNotFoundError: No module named 'NBA'
[2024-06-02T20:40:54.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:54.358+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.073 seconds
[2024-06-02T20:40:56.170+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:56.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:40:56.173+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:40:56.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:56.707+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:40:56.698+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:40:56.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:40:56.740+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.575 seconds
[2024-06-02T20:41:27.259+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:41:27.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:41:27.264+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:41:27.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:41:27.622+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:41:27.612+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:41:27.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:41:27.670+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.421 seconds
[2024-06-02T20:42:10.730+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:42:10.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:42:10.737+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:42:10.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:42:11.184+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:42:11.174+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:42:11.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:42:11.232+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.525 seconds
[2024-06-02T20:42:44.003+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:42:44.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:42:44.093+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:42:44.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:42:46.722+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:42:46.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:42:46.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:42:46.799+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 2.843 seconds
[2024-06-02T20:43:17.189+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:43:17.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:43:17.194+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:43:17.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:43:17.532+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:43:17.525+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:43:17.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:43:17.561+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.380 seconds
[2024-06-02T20:43:48.817+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:43:48.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:43:48.853+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:43:48.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:43:50.214+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:43:50.180+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:43:50.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:43:50.363+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 1.596 seconds
[2024-06-02T20:44:20.619+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:44:20.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:44:20.634+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:44:20.633+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:44:21.430+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:44:21.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:44:21.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:44:21.507+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.944 seconds
[2024-06-02T20:44:52.204+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:44:52.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:44:52.209+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:44:52.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:44:52.954+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:44:52.933+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:44:52.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:44:53.040+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.854 seconds
[2024-06-02T20:45:24.139+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:45:24.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:45:24.143+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:45:24.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:45:24.604+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:45:24.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:45:24.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:45:24.660+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.532 seconds
[2024-06-02T20:45:55.190+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:45:55.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:45:55.195+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:45:55.195+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:45:55.862+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:45:55.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:45:55.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:45:55.960+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.782 seconds
[2024-06-02T20:46:26.538+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:46:26.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:46:26.546+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:46:26.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:46:27.036+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:46:27.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:46:27.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:46:27.109+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.577 seconds
[2024-06-02T20:46:57.604+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:46:57.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:46:57.608+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:46:57.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:46:58.588+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:46:58.569+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:46:58.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:46:58.679+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 1.092 seconds
[2024-06-02T20:47:28.934+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:47:28.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:47:28.939+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:47:28.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:47:29.605+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:47:29.589+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:47:29.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:47:29.698+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.793 seconds
[2024-06-02T20:48:00.239+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:48:00.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:48:00.242+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:48:00.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:48:01.023+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:48:01.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:48:01.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:48:01.135+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.912 seconds
[2024-06-02T20:48:31.643+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:48:31.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:48:31.647+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:48:31.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:48:32.165+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:48:32.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:48:32.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:48:32.227+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.595 seconds
[2024-06-02T20:49:03.918+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:49:03.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:49:03.937+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:49:03.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:49:06.094+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:49:06.069+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:49:06.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:49:06.197+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 2.297 seconds
[2024-06-02T20:49:36.931+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:49:36.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:49:36.944+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:49:36.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:49:37.748+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:49:37.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:49:37.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:49:37.846+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.925 seconds
[2024-06-02T20:50:08.608+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:50:08.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:50:08.622+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:50:08.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:50:09.207+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:50:09.190+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:50:09.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:50:09.282+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.692 seconds
[2024-06-02T20:50:39.561+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:50:39.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:50:39.565+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:50:39.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:50:40.212+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:50:40.194+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:50:40.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:50:40.314+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.767 seconds
[2024-06-02T20:51:10.479+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:51:10.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:51:10.485+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:51:10.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:51:12.074+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:51:12.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:51:12.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:51:12.182+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 1.718 seconds
[2024-06-02T20:51:42.499+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:51:42.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:51:42.506+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:51:42.505+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:51:42.936+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:51:42.926+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:51:42.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:51:42.977+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.491 seconds
[2024-06-02T20:52:13.525+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:52:13.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:52:13.530+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:52:13.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:52:13.814+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:52:13.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:52:13.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:52:13.844+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.326 seconds
[2024-06-02T20:52:44.408+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:52:44.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:52:44.411+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:52:44.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:52:44.695+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:52:44.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:52:44.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:52:44.743+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.340 seconds
[2024-06-02T20:53:15.451+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:53:15.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:53:15.455+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:53:15.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:53:15.759+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:53:15.750+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:53:15.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:53:15.798+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.353 seconds
[2024-06-02T20:53:46.511+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:53:46.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:53:46.513+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:53:46.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:53:46.798+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:53:46.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:53:46.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:53:46.829+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.323 seconds
[2024-06-02T20:54:17.195+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:54:17.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:54:17.200+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:54:17.200+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:54:17.504+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:54:17.496+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:54:17.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:54:17.534+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.345 seconds
[2024-06-02T20:54:47.997+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:54:47.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:54:48.002+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:54:48.001+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:54:48.376+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:54:48.368+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:54:48.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:54:48.411+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.420 seconds
[2024-06-02T20:55:18.593+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:55:18.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:55:18.596+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:55:18.596+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:55:18.937+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:55:18.929+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:55:18.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:55:18.974+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.387 seconds
[2024-06-02T20:55:49.265+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:55:49.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:55:49.268+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:55:49.268+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:55:49.595+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:55:49.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:55:49.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:55:49.626+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.368 seconds
[2024-06-02T20:56:19.854+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:56:19.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/NBA_dag/NBA_dag.py for tasks to queue
[2024-06-02T20:56:19.857+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:56:19.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:56:20.184+0000] {logging_mixin.py:188} INFO - [2024-06-02T20:56:20.175+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/NBA_dag/NBA_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/NBA_dag/NBA_dag.py", line 6, in <module>
    from NBA_etl import run_nba_etl
  File "/opt/airflow/NBA_dag/NBA_etl.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-02T20:56:20.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/NBA_dag/NBA_dag.py
[2024-06-02T20:56:20.213+0000] {processor.py:183} INFO - Processing /opt/airflow/NBA_dag/NBA_dag.py took 0.367 seconds
